name: 自动签到
 
on:
    push:
        branches:
            - main
    schedule:
        - cron: '1 16 * * *'
env:
    TZ: Asia/Shanghai

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@main
            - name: Set go
              uses: actions/setup-go@v5
              with:
                go-version: '1.16.1'
            - name: hifini auto sign in
              env:
                COOKIE: ${{ secrets.COOKIE }}
              run: go run main.go
